config:
    paths:
        'orolocalizedemailtemplates/js/app/components/localized-template-fallback-component': 'bundles/orolocalizedemailtemplates/js/app/components/localized-template-fallback-component.js'
