services:
    oro_localized_email_templates.manager.localization_aware_email_notification:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Manager\LocalizationAwareEmailNotificationManager'
        public: true
        decorates: 'oro_notification.manager.email_notification'
        arguments:
            - '@oro_notification.manager.email_notification_sender'
            - '@logger'
            - '@oro_localized_email_templates.provider.localized_template'

    oro_localized_email_templates.manager.localization_aware_email_template:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Manager\LocalizationAwareEmailTemplateManager'
        public: true
        decorates: 'oro_email.manager.template_email'
        arguments:
            - '@oro_email.direct_mailer'
            - '@oro_email.mailer.processor'
            - '@oro_localized_email_templates.provider.localized_template'

    oro_localized_email_templates.provider.localized_template:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\LocalizedTemplateProvider'
        public: false
        arguments:
            - '@oro_localized_email_templates.provider.preferred_localization_provider'
            - '@oro_localized_email_templates.provider.email_template_content_provider'

    oro_localized_email_templates.provider.email_template_content_provider:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\LocalizationAwareEmailTemplateContentProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@oro_email.email_renderer'
            - '@property_accessor'
            - '@logger'
            - '@stof_doctrine_extensions.listener.translatable'

    oro_localized_email_templates.action.send_email_template:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Action\LocalizationAwareSendEmailTemplate'
        public: true
        decorates: 'oro_email.workflow.action.send_email_template'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@oro_email.mailer.processor'
            - '@oro_email.email.address.helper'
            - '@oro_entity.entity_name_resolver'
            - '@doctrine'
            - '@validator'
            - '@oro_localized_email_templates.provider.localized_template'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: oro_action.action, alias: send_email_template }

    oro_localized_email_templates.action.send_order_confirmation_email:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Action\SendOrderConfirmationEmail'
        public: true
        decorates: 'oro_checkout.action.send_order_confirmation_email'
        parent: oro_localized_email_templates.workflow.action.send_email_template
        tags:
            - { name: oro_action.action, alias: send_order_confirmation_email }

    # Forms
    oro_localized_email_templates.form.extension.localized_aware_email_template_type:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Form\Extension\LocalizationAwareEmailTemplateTypeExtension'
        public: true
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: form.type_extension, alias: form, extended_type: 'Oro\Bundle\EmailBundle\Form\Type\EmailTemplateType' }

    oro_localized_email_templates.form.email_template_localization_type:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Form\EmailTemplateLocalizationType'
        public: true
        arguments:
            - '@translator'
            - '@oro_locale.manager.localization'
        tags:
            - { name: form.type }
