services:
    oro_localized_email_templates.manager.localization_aware_email_template:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Manager\LocalizationAwareEmailTemplateManager'
        public: true
        decorates: 'oro_email.manager.template_email'
        arguments:
            - '@oro_email.direct_mailer'
            - '@oro_localized_email_templates.provider.preferred_localization_provider'
            - '@oro_email.mailer.processor'
            - '@oro_localized_email_templates.provider.email_template_content_provider'

    oro_localized_email_templates.provider.preferred_localization_provider:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\PreferredLocalizationProvider\ChainPreferredLocalizationProvider'
        public: false
        arguments:
            - !tagged oro_localized_email_templates.preferred_localization_provider

    Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\PreferredLocalizationProvider\PreferredLocalizationProviderInterface:
        alias: 'oro_localized_email_templates.provider.preferred_localization_provider'

    oro_localized_email_templates.provider.preferrer_localization_provider.default:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\PreferredLocalizationProvider\DefaultPreferredLocalizationProvider'
        public: false
        arguments:
            - '@oro_locale.manager.localization'
        tags:
            - { name: oro_localized_email_templates.preferred_localization_provider, priority: 255 }

    oro_localized_email_templates.provider.email_template_content_provider:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Provider\LocalizationAwareEmailTemplateContentProvider'
        public: false
        arguments:
            - '@doctrine'
            - '@oro_email.email_renderer'
            - '@logger'

    # Forms
    oro_localized_email_templates.form.extension.localized_aware_email_template_type:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Form\Extension\LocalizationAwareEmailTemplateTypeExtension'
        public: true
        arguments:
            - '@oro_config.user'
            - '@oro_locale.settings'
            - '@oro_locale.manager.localization'
        tags:
            - { name: form.type_extension, alias: form, extended_type: 'Oro\Bundle\EmailBundle\Form\Type\EmailTemplateType' }

    oro_localized_email_templates.form.email_template_localization_type:
        class: 'Oro\Bundle\LocalizedEmailTemplatesBundle\Form\EmailTemplateLocalizationType'
        public: true
        arguments:
            - '@translator'
        tags:
            - { name: form.type }
